# Generated by Django 4.2.3 on 2023-07-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_mascotas', '0002_cuentas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='imagen',
            field=models.ImageField(upload_to='cuentas/', verbose_name='Imagen'),
        ),
    ]
