# Generated by Django 4.2.3 on 2023-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_mascotas', '0003_alter_cuentas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='tipo_cuenta',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=50, verbose_name='Tipo cuenta'),
        ),
    ]
