# Generated by Django 4.2.3 on 2023-07-10 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_mascotas', '0005_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('nro_boleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nro boleta')),
                ('monto_sin_iva', models.IntegerField(verbose_name='Monto sin IVA')),
                ('iva', models.IntegerField(verbose_name='IVA')),
                ('total_a_pagar', models.IntegerField(verbose_name='Total a pagar')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de venta')),
                ('fecha_despacho', models.DateField(blank=True, null=True, verbose_name='Fecha de despacho')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('estado', models.CharField(choices=[('Anulado', 'Anulado'), ('Vendido', 'Vendido'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado')], max_length=50, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_mascotas.cuentas')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'db_table': 'Boleta',
            },
        ),
        migrations.AlterModelOptions(
            name='bodega',
            options={'verbose_name': 'Bodega', 'verbose_name_plural': 'Productos en bodega'},
        ),
        migrations.CreateModel(
            name='detalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descuento_subscriptor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto subs')),
                ('descuento_oferta', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto oferta')),
                ('descuento_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descto total')),
                ('descuentos', models.IntegerField(verbose_name='Descuentos')),
                ('precio_a_pagar', models.IntegerField(verbose_name='Precio a pagar')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_mascotas.bodega')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_mascotas.boleta')),
            ],
            options={
                'verbose_name': 'Detalle de boleta',
                'verbose_name_plural': 'Detalles de boletas',
                'db_table': 'detalleBoleta',
            },
        ),
    ]
